display:
  background:
    path: /usr/share/thermalright-lcd-control/themes/backgrounds/y010.png
    type: image
  date:
    color: '#FFC130FF'
    enabled: true
    font_size: 24
    position:
      x: 15
      y: 3
    text: ''
  foreground:
    alpha: 1.0
    enabled: true
    path: /usr/share/thermalright-lcd-control/themes/foregrounds/{resolution}/006b.png
    position:
      x: 0
      y: 0
  metrics:
    configs:
    - color: '#FFC130FF'
      enabled: true
      font_size: 24
      format_string: '{label}{value}{unit}'
      label: ''
      name: cpu_temperature
      position:
        x: 54
        y: 143
      unit: °
    - color: '#FFC130FF'
      enabled: true
      font_size: 24
      format_string: '{label}{value}{unit}'
      label: ''
      name: gpu_temperature
      position:
        x: 255
        y: 141
      unit: °
    - color: '#FFC130FF'
      enabled: true
      font_size: 24
      format_string: '{label}{value}{unit}'
      label: ''
      name: cpu_frequency
      position:
        x: 90
        y: 71
      unit: MHZ
    - color: '#FFC130FF'
      enabled: true
      font_size: 24
      format_string: '{label}{value}{unit}'
      label: ''
      name: gpu_frequency
      position:
        x: 105
        y: 210
      unit: MHZ
    enabled: true
  time:
    color: '#FFC130FF'
    enabled: true
    font_size: 24
    position:
      x: 155
      y: 141
    text: ''
